name: Add User from Issues

on:
  issues:
    types: [labeled]

jobs:
  create-invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name get email
        uses: jasonmacgowan/actions-parse-issue
        env:
          ADMIN_TOKEN: ${{secrets.ADMIN_TOKEN}}
