name: Add User from Issues

on:
  issues:
    types: [labeled]

jobs:
  create-invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: npm install
      - name: Get issue data
        uses: froi/add_invite_user@remove_username
        with:
          PARSING_RULES_PATH: ".github/parsing_rules.json"
          USER_ROLE: "direct_member"
        env:
          ADMIN_TOKEN: ${{secrets.ADMIN_TOKEN}}
