name: Add User from Issues

on:
  issues:
    types: [labeled]

jobs:
  create-invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get email
        uses: jasonmacgowan/actions-parse-issue@master
        with:
          extract_email: '<p>Email of Requester:\s*(.*)</p>'
        id: get_input
        env:
          ADMIN_TOKEN: ${{secrets.ADMIN_TOKEN}}
      - name: invite user
        uses: froi/add_invite_user@change_input_release
        id: invite_user
        with:
          EMAIL: ${{ steps.get_input.outputs['email'] }}
          CONFIG_PATH: ".github/parsing_rules.json"
        env: 
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
      - name: Comment on Issue
        uses: froi/add-comment-action@release/v1
        with:
          message: ${{ steps.get-issue-data.message }}
          status: ${{ steps.get-issue-data.stepStatus }}
        env: 
          GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
