name: Add User from Issues

on:
  issues:
    types: [labeled]

jobs:
  create-invite:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: get email
        uses: jasonmacgowan/actions-parse-issue@master
        id: get_input
        env:
          ADMIN_TOKEN: ${{secrets.ADMIN_TOKEN}}
      - name: invite user
        uses: froi/add_invite_user@change_input_release
        id: invite_user
        with:
          EMAIL: ${{ steps.get_input["<p>Email_of_Requester"] }}
        env: 
          ADMIN_TOKEN: ${{ secrets.ADMIN_TOKEN }}
